spring:
  application:
    name: shop
  profiles:
    active: dev
rpc:
  user:
    version: 1.0
dubbo:
  # Dubbo 注册中心
  registry:
    #    address: spring-cloud://400-infra.server.iocoder.cn:8848 # 指定 Dubbo 服务注册中心的地址
    address: nacos://localhost:8848 #?namespace=dev # 指定 Dubbo 服务注册中心的地址
